name: RST Check

on: [push, pull_request]

jobs:
  build_wheels:
    name: rstcheck ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      # Used to host cibuildwheel
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install requirements
        run: python -m pip install -r requirements.txt

      - name: Install rstcheck
        run: python -m pip install sphinx tomli rstcheck[toml,sphinx]

      - name: rstcheck
        run: rstcheck -r _doc mlinsights
