name: Build Wheel Windows

on:
  push:
    branches:
      - main
      - 'releases/**'

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v3

      # Used to host cibuildwheel
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: python version
        run: python -V

      - name: Build wheels
        run: python -m cibuildwheel
        # to supply options, put them in 'env', like:
        # env:
        #   CIBW_BUILD: cp310-win_amd64* cp311-win_amd64*

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
