name: Build Wheel Windows

on:
  push:
#    branches:
#      - main
#      - 'releases/**'
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v4

      # Used to host cibuildwheel
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: python version
        run: python -V

      - name: Build wheels
        run: python -m cibuildwheel

      - uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl
